### ISSUE TITLE
User Story: User-Friendly Navigation

### ISSUE THREAD

**Issue by Carlos-n21** [Francisca-Heii/Dec-2024-Hackathon#41]
As a user, I want the website to have user-friendly navigation, so that I can find recipes and other content quickly and easily.

**Acceptance Criteria:**

- [x] The website features a clear and intuitive menu structure.
- [x] Navigation links are easy to find and use.
- [x] Important sections (e.g., different recipes, search) are easily accessible from any page.

**Tasks:**

- [x] Design a main navigation menu that is easy to understand and use.
- [x] Implement a sticky header to keep navigation links accessible as users scroll.
- [x] Conduct usability testing to identify and address any navigation issues.
